[package]
name = "xcm-simulator-example"
description = "Examples of xcm-simulator usage."
authors.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
codec = { package = "parity-scale-codec", version = "3.3.0" }
scale-info = { version = "2.1.2", features = ["derive"] }
log = { version = "0.4.14", default-features = false }

frame-system = { git = "https://github.com/InfraBlockchain/infra-substrate", branch = "master" }
frame-support = { git = "https://github.com/InfraBlockchain/infra-substrate", branch = "master" }
pallet-balances = { git = "https://github.com/InfraBlockchain/infra-substrate", branch = "master" }
pallet-uniques = { git = "https://github.com/InfraBlockchain/infra-substrate", branch = "master" }
sp-std = { git = "https://github.com/InfraBlockchain/infra-substrate", branch = "master" }
sp-core = { git = "https://github.com/InfraBlockchain/infra-substrate", branch = "master" }
sp-runtime = { git = "https://github.com/InfraBlockchain/infra-substrate", branch = "master" }
sp-io = { git = "https://github.com/InfraBlockchain/infra-substrate", branch = "master" }
sp-tracing = { git = "https://github.com/InfraBlockchain/infra-substrate", branch = "master" }

xcm = { path = "../../" }
xcm-simulator = { path = "../" }
xcm-executor = { path = "../../xcm-executor" }
xcm-builder = { path = "../../xcm-builder" }
pallet-xcm = { path = "../../pallet-xcm" }
infrablockspace-core-primitives = { path = "../../../core-primitives" }
infrablockspace-runtime-parachains = { path = "../../../runtime/parachains" }
infrablockspace-parachain = { path = "../../../parachain" }

[features]
default = []
runtime-benchmarks = [
	"frame-system/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"pallet-uniques/runtime-benchmarks",
	"pallet-xcm/runtime-benchmarks",
	"xcm-builder/runtime-benchmarks",
	"xcm-executor/runtime-benchmarks",
	"infrablockspace-runtime-parachains/runtime-benchmarks",
	"infrablockspace-parachain/runtime-benchmarks",
]
