[package]
name = "test-parachain-undying-collator"
description = "Collator for the undying test parachain"
edition.workspace = true
version.workspace = true
authors.workspace = true

[[bin]]
name = "undying-collator"
path = "src/main.rs"

[[bin]]
name = "undying_collator_puppet_worker"
path = "bin/puppet_worker.rs"

[dependencies]
parity-scale-codec = { version = "3.3.0", default-features = false, features = ["derive"] }
clap = { version = "4.0.9", features = ["derive"] }
futures = "0.3.19"
futures-timer = "3.0.2"
log = "0.4.17"

test-parachain-undying = { path = ".." }
infrablockspace-primitives = { path = "../../../../primitives" }
infrablockspace-cli = { path = "../../../../cli" }
infrablockspace-service = { path = "../../../../node/service", features = ["rococo-native"] }
infrablockspace-node-primitives = { path = "../../../../node/primitives" }
infrablockspace-node-subsystem = { path = "../../../../node/subsystem" }

sc-cli = { git = "https://github.com/InfraBlockchain/infra-substrate", branch = "master" }
sp-core = { git = "https://github.com/InfraBlockchain/infra-substrate", branch = "master" }
sc-service = { git = "https://github.com/InfraBlockchain/infra-substrate", branch = "master" }

# This one is tricky. Even though it is not used directly by the collator, we still need it for the
# `puppet_worker` binary, which is required for the integration test. However, this shouldn't be
# a big problem since it is used transitively anyway.
infrablockspace-node-core-pvf = { path = "../../../../node/core/pvf" }

[dev-dependencies]
infrablockspace-parachain = { path = "../../.." }
infrabs-test-service = { path = "../../../../node/test/service" }

substrate-test-utils = { git = "https://github.com/InfraBlockchain/infra-substrate", branch = "master" }
sc-service = { git = "https://github.com/InfraBlockchain/infra-substrate", branch = "master" }
sp-keyring = { git = "https://github.com/InfraBlockchain/infra-substrate", branch = "master" }

tokio = { version = "1.24.2", features = ["macros"] }
