[package]
name = "xcm-executor-integration-tests"
description = "Integration tests for the XCM Executor"
authors.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
frame-support = { git = "https://github.com/InfraBlockchain/infra-substrate", branch = "master", default-features = false }
frame-system = { git = "https://github.com/InfraBlockchain/infra-substrate", branch = "master" }
futures = "0.3.21"
pallet-xcm = { path = "../../pallet-xcm" }
infrablockspace-test-runtime = { path = "../../../runtime/test-runtime" }
sp-consensus = { git = "https://github.com/InfraBlockchain/infra-substrate", branch = "master" }
sp-keyring = { git = "https://github.com/InfraBlockchain/infra-substrate", branch = "master" }
sp-runtime = { git = "https://github.com/InfraBlockchain/infra-substrate", branch = "master", default-features = false }
sp-state-machine = { git = "https://github.com/InfraBlockchain/infra-substrate", branch = "master" }
xcm = { path = "../..", default-features = false }
xcm-executor = { path = ".." }
sp-tracing = { git = "https://github.com/InfraBlockchain/infra-substrate", branch = "master" }

[features]
default = ["std"]
std = ["xcm/std", "sp-runtime/std", "frame-support/std"]
