[package]
name = "remote-ext-tests-bags-list"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
infrablockspace-runtime = { path = "../../../runtime/infrablockspace" }
kusama-runtime = { path = "../../../runtime/kusama" }
infrablockspace-runtime-constants = { path = "../../../runtime/infrablockspace/constants" }
kusama-runtime-constants = { path = "../../../runtime/kusama/constants" }

pallet-bags-list-remote-tests = { git = "https://github.com/InfraBlockchain/infra-substrate", branch = "master" }
sp-tracing = { git = "https://github.com/InfraBlockchain/infra-substrate", branch = "master" }
frame-system = { git = "https://github.com/InfraBlockchain/infra-substrate", branch = "master" }
sp-core = { git = "https://github.com/InfraBlockchain/infra-substrate", branch = "master" }

clap = { version = "4.0.9", features = ["derive"] }
log = "0.4.17"
tokio = { version = "1.24.2", features = ["macros"] }
