[package]
name = "infrablockspace-node-network-protocol"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "Primitives types for the Node-side"

[dependencies]
async-trait = "0.1.57"
hex = "0.4.3"
infrablockspace-primitives = { path = "../../../primitives" }
infrablockspace-node-primitives = { path = "../../primitives" }
polkadot-node-jaeger = { path = "../../jaeger" }
parity-scale-codec = { version = "3.3.0", default-features = false, features = ["derive"] }
sc-network = { git = "https://github.com/InfraBlockchain/infra-substrate", branch = "master" }
sc-network-common = { git = "https://github.com/InfraBlockchain/infra-substrate", branch = "master" }
sc-authority-discovery = { git = "https://github.com/InfraBlockchain/infra-substrate", branch = "master" }
strum = { version = "0.24", features = ["derive"] }
futures = "0.3.21"
thiserror = "1.0.31"
fatality = "0.0.6"
rand = "0.8"
derive_more = "0.99"
gum = { package = "tracing-gum", path = "../../gum" }

[dev-dependencies]
rand_chacha = "0.3.1"
